### ISSUE TITLE
Modify the credential screen to compare current DID creds in the app with that of published DID creds

### ISSUE THREAD

**Issue by kpachhai** [elastos/Elastos.Trinity.DApps.DID#10]
Occasionally, fetch the latest DID document from the DID sidechain and compare with the DID document on the app. If they don’t match, show a message next to each credential on the page that the DID document is not up-to-date on the blockchain. And ask the user to publish it if so.

Show something like the following next to each credential:
- If it's a new credential was added, show "This credential is not published on the blockchain"
- If it's an updated credential that is different, show "This credential is different than the one on the blockchain"

**Comment by BenjaminPiette** [comment]
We have already started to to that using the DID app background service. DID is synchronized from time to time.

The missing part is, for now we do not write any DID document conflict handler and we simply force to overwrite the did document. In reality, we already have a task here with some info about this: https://app.clickup.com/t/3frc97

The summary is as following:

- Write a conflict handler for synchronize()
- In case of conflict, we use the most recent document (locally modified VS published date).
- The local did document should merge chain did document's metadata to not show the "not up to date" error next time we publish (You can get more details about what this means from Jingyu - but basically if you keep the local version without merging metadata from the chain document, next publish will fail. SO you need to keep the local data, with the chain metadata).

**Comment by martintuum** [comment]
Small notification cards for a visual indication on the home screen I think can be a good option for this. Shown in the example here.
The placement of these are just under your main header identity. A cross or swipe to dismiss maybe? Click to start that action with whatever it is we need to do - this example - publish Identity so its up to date.

Or would it make sense to use the elastOS notifications instead or as well?

**Comment by martintuum** [comment]
<img width="444" alt="Screenshot 2020-08-19 at 16 48 55" src="https://user-images.githubusercontent.com/58228076/90658808-e6b83080-e23b-11ea-9549-bdff25aebf8f.png">

**Comment by martintuum** [comment]
<img width="483" alt="Screenshot 2020-08-19 at 16 49 00" src="https://user-images.githubusercontent.com/58228076/90658826-ec157b00-e23b-11ea-8c79-aee671d7e302.png">

**Comment by wakqasahmed** [comment]
@kpachhai regarding the first point, 

`If it's a new credential was added, show "This credential is not published on the blockchain"`

is it possible to set visibility of individual credentials locally and not publish it? e.g. Email is published (means also visible) but name's visibility to be set as true without publishing to blockchain.
