### ISSUE TITLE
The display under "Current Options" is not beautiful and needs to be adjusted

### ISSUE THREAD

**Issue by xuliting** [elastos/Elastos.Trinity.DApps.DID#100]
![31211606275935_ pic_hd](https://user-images.githubusercontent.com/18321471/100180731-c7ecc880-2f13-11eb-93eb-814bb29e340e.jpg)

**Comment by dchagastelles** [comment]
![image](https://user-images.githubusercontent.com/4438399/100767857-3cb67b80-33c8-11eb-9563-64f7ac8c5480.png)

I've scaled down the images and kinda squeezed the content to fit. The imaged is in a Nexus 4 (768 x 1280 resolution, which is the lowest I found in the android emulator).

**Comment by xuliting** [comment]
ok
