### ISSUE TITLE
Edit profile interface: "Show on Profile" is best displayed on one line

### ISSUE THREAD

**Issue by xuliting** [elastos/Elastos.Trinity.DApps.DID#101]
![31221606276067_ pic_hd](https://user-images.githubusercontent.com/18321471/100181348-f7e89b80-2f14-11eb-8d91-0ae4e142e34d.jpg)

**Comment by dchagastelles** [comment]
Its possibly better in one line, but its not to me to say. It was implemented like the design by Martin Knight. 

![image](https://user-images.githubusercontent.com/4438399/100794958-45b94400-33ec-11eb-9faa-6c1e54d64901.png)

@kpachhai should I change this one?

**Comment by kpachhai** [comment]
Yes let's change this to be in one line as that is cleaner

**Comment by xuliting** [comment]
Verified
