### ISSUE TITLE
DID has not been published on the chain, an error is reported after opening Identity (occasionally), and an error (getservice) is reported by clicking the "Profile" tab page (must appear)

### ISSUE THREAD

**Issue by xuliting** [elastos/Elastos.Trinity.DApps.DID#108]
<img width="1419" alt="截屏2020-11-26 11 33 08" src="https://user-images.githubusercontent.com/18321471/100306637-d05e0580-2fde-11eb-964d-788e02e1aaff.png">
<img width="1422" alt="截屏2020-11-26 11 34 14" src="https://user-images.githubusercontent.com/18321471/100306683-e2d83f00-2fde-11eb-862e-112625522491.png">

**Comment by xuliting** [comment]
The published DID on the chain: When the information is not loaded, clicking "profile" will also report an error (getservices)

**Comment by raozhiming** [comment]
fixed

**Comment by xuliting** [comment]
Verified
