### ISSUE TITLE
Check the expiry date whenever “credaccess” is called by another app

### ISSUE THREAD

**Issue by kpachhai** [elastos/Elastos.Trinity.DApps.DID#11]
This doesn’t apply to “self-proclaimed” credential as it doesn't make sense to have it be enforced on such a loose credential type.

When third party capsules or dApps request a particular credential type such as email, first check whether the credential has expired. If expired, dApps cannot fetch the expired credential. Note: The following is how the expiration is defined for each credential:
- Expiration date attribute of the credential
- Expiration date of owner’s DID
- Expiration date of issuer’s DID

**Comment by BenjaminPiette** [comment]
"This doesn’t apply to “self-proclaimed” credential" but still, self claimed credentials can expire. What we should do here I think is at the time credaccess is called, for all self claimed credentials, if they are expired or about to expire, we should simply re-issue them locally.

Note: we may also have to publish the DID document for published credentials then.
