### ISSUE TITLE
Credentials: Click to publish from an unpublished information detail page. When selecting a wallet, it is unknown what content has been published.

### ISSUE THREAD

**Issue by xuliting** [elastos/Elastos.Trinity.DApps.DID#110]

**Comment by dchagastelles** [comment]
@kpachhai Wouldn't it be responsibility of the wallet to show what has been published the same way Assist do?

**Comment by kpachhai** [comment]
Yea. I think its better to implement this from wallet app, not from Identity app

**Comment by BenjaminPiette** [comment]
@xuliting I think you mixed the two apps here. The screen showing the publish confirmation (need to pay a few fees, etc) is actually in the wallet app, so this feature should be in the wallet app. You may close this task here and open one in clickup for the wallet app.

**Comment by xuliting** [comment]
close
