### ISSUE TITLE
Add extra info to existing field get overridden and become empty

### ISSUE THREAD

**Issue by jmsaulnier** [elastos/Elastos.Trinity.DApps.DID#3]
## Current Behavior
if user add info field, and it already exists (eg: name) - input value is overridden and become empty

## Expected Behavior
User shouldn't be able to add extra info field if already in the list / completed

@BenjaminPiette

**Comment by BenjaminPiette** [comment]
Added to our bug tracking tool thanks

**Comment by BenjaminPiette** [comment]
Fixed. We can now add only items that don't exist.
