### ISSUE TITLE
Only show "Verify now" button to the default profile fields on Identity app

### ISSUE THREAD

**Issue by kpachhai** [elastos/Elastos.Trinity.DApps.DID#34]
There are credentials that are issued from applications such as Academy app. It doesn't make sense for us to have this button for these kind of credentials.

**Comment by wakqasahmed** [comment]
Does that mean "Verify Now" button be hidden for the capsule credentials e.g. elastos-academy, vouch, assist, or any other capsule which is listed under Capsules tab?

**Comment by kpachhai** [comment]
Yes
