### ISSUE TITLE
Show which credentials are verified and which are not on Identity app

### ISSUE THREAD

**Issue by kpachhai** [elastos/Elastos.Trinity.DApps.DID#4]
Show which credentials are verified and which are not. If verified, show the issuer DID for the verified credential. 

If a credential such as email is verified by another validator, retrieve the “Name” field for the issuer DID from the blockchain if published including their avatar. So, in addition to showing the issuer DID for the verified credential, we also show other info about that particular DID such as issuer name, issuer avatar, and any other relevant information. 

This is to improve the UI for each issuer.

**Comment by BenjaminPiette** [comment]
Please note that there could be no name in the resolved DID.
