### ISSUE TITLE
Some phones do not display two icons on a row

### ISSUE THREAD

**Issue by xuliting** [elastos/Elastos.Trinity.DApps.DID#45]
![28881602491011_ pic](https://user-images.githubusercontent.com/18321471/95723270-8972b580-0ca7-11eb-9710-f49043c626d9.jpg)

eg: iphone 11
      oppo A11    PCHM10

**Comment by dchagastelles** [comment]
The button disposition depends on the resolutiona and the button adjust accordingly. Tel me what is the minimum resolution we should make fit 2 buttons in a row and I can try to make it fit.But if the lower resolution eventually we will end with a single collumn.

**Comment by xuliting** [comment]
iphone 11
huawei mate 10 pro
oppo A11

**Comment by martintuum** [comment]
We have re-designed around this and got rid of all these more option pop ups anyway so we will not have these screens.

**Comment by xuliting** [comment]
The design has been changed and can be closed
