### ISSUE TITLE
Profile page: After the address page pops up, the button below is not displayed completely and cannot be clicked to view.

### ISSUE THREAD

**Issue by xuliting** [elastos/Elastos.Trinity.DApps.DID#48]
![28751602475218_ pic_hd](https://user-images.githubusercontent.com/18321471/95727188-70203800-0cac-11eb-8b5f-dd91f2ccc6c9.jpg)

**Comment by xuliting** [comment]
Verified

**Comment by xuliting** [comment]
unsolved
![Uploading 17791602655888_.pic_hd.jpg…]()

**Comment by dchagastelles** [comment]
What is the screen resolution? So I can reproduce the issue, tks.

**Comment by kpachhai** [comment]
@xuliting Could you let us know your screen size? Because this may be an issue on certain resolutions such as the one you're testing with.

**Comment by xuliting** [comment]
now is ok.
verified
