### ISSUE TITLE
After editing the DID information, directly click the return icon; after returning to the previous interface, the displayed information "Wait   a moment" is redundant

### ISSUE THREAD

**Issue by xuliting** [elastos/Elastos.Trinity.DApps.DID#58]

**Comment by kpachhai** [comment]
This is because when you click on back button, it saves the information. This is to let the user know that some info was saved. The "Wait a moment" screen is a loading screen so in case something goes wrong, the user will know whether the info was really saved or not.

**Comment by xuliting** [comment]
> This is because when you click on back button, it saves the information. This is to let the user know that some info was saved. The "Wait a moment" screen is a loading screen so in case something goes wrong, the user will know whether the info was really saved or not.

What I mean is, you don’t need to save when you click the back button. You only need to save when you click the save button.

**Comment by xuliting** [comment]
Because it’s the ben’s previously added click to return and save it, I will close this issue.
