### ISSUE TITLE
Credentials: On the details page of a certain DID information, select the information not to be public, but the information under "Current Actions" still exists

### ISSUE THREAD

**Issue by xuliting** [elastos/Elastos.Trinity.DApps.DID#59]
![28991602672077_ pic_hd](https://user-images.githubusercontent.com/18321471/95978703-1c008980-0e4d-11eb-9f06-f65046f26650.jpg)

**Comment by kpachhai** [comment]
Being public has nothing to do with whether a cred needs to be verified. That banner to verify will always show up if a cred has not been verified yet - whether it is visible or not doesn't matter.

**Comment by xuliting** [comment]
If the operation has nothing to do with whether it is visible, then the "Current Actions" field cannot be displayed with the switch
![29061602737097_ pic_hd](https://user-images.githubusercontent.com/18321471/96078232-5406db80-0ee4-11eb-969b-641b20ee0629.jpg)
![29071602737107_ pic_hd](https://user-images.githubusercontent.com/18321471/96078235-5832f900-0ee4-11eb-8a79-a25c1a798027.jpg)

**Comment by xuliting** [comment]
Verified
