### ISSUE TITLE
Credentials: In the details page of a certain DID information, if you click the button behind whether to choose to publish multiple times, accidentally crash or report an error

### ISSUE THREAD

**Issue by xuliting** [elastos/Elastos.Trinity.DApps.DID#61]
![29011602673012_ pic](https://user-images.githubusercontent.com/18321471/95980013-1e63e300-0e4f-11eb-8778-b464b00d32bb.jpg)

**Comment by dchagastelles** [comment]
Tried to reproduce with new version and wasn't able to do it. Possibly solved.

**Comment by kpachhai** [comment]
Can you recheck this issue @dchagastelles ?

**Comment by xuliting** [comment]
unsolved

**Comment by xuliting** [comment]
<img width="1418" alt="截屏2020-11-26 14 09 59" src="https://user-images.githubusercontent.com/18321471/100314223-1cb24100-2ff1-11eb-99bb-a20c48e9c00b.png">

**Comment by xuliting** [comment]
<img width="1414" alt="截屏2020-11-26 14 11 31" src="https://user-images.githubusercontent.com/18321471/100314338-61d67300-2ff1-11eb-9612-cd9b2104771c.png">

**Comment by kpachhai** [comment]
Is this problem s till here with the latest update @xuliting

**Comment by dchagastelles** [comment]
@xuliting I just tried to reproduce the error in the edit profile page based on the images you shared. I have added, removed and modified multiple fields, using the toggle extensively but had no error. If you still is capable of reproduce, could you describe in detail how you do it or maybe send me a small video.

**Comment by xuliting** [comment]
@dchagastelles , now there is no button to choose whether to show on Credential page.so i close it .
