### ISSUE TITLE
"Weibo" missing icon

### ISSUE THREAD

**Issue by xuliting** [elastos/Elastos.Trinity.DApps.DID#63]
![29031602732071_ pic_hd](https://user-images.githubusercontent.com/18321471/96073626-62032f00-0ed9-11eb-8745-dc88fa41aebc.jpg)

**Comment by dchagastelles** [comment]
Weibo removed from basic credential. Weibo icon not in our design so we need a logo

**Comment by dchagastelles** [comment]
Added missing weibo icon

**Comment by xuliting** [comment]
Verified
