### ISSUE TITLE
After editing the DID information, if you choose to return, please do not save the information

### ISSUE THREAD

**Issue by xuliting** [elastos/Elastos.Trinity.DApps.DID#69]

**Comment by dchagastelles** [comment]
Need a definition if we save on leave or not.

**Comment by kpachhai** [comment]
@xuliting what's the issue? Are you saying we shouldn't save DID info if user goes back after adding something? We had added this option as per @BenjaminPiette's suggestion(where he wanted to save info even when pressing back button). Please clarify

**Comment by xuliting** [comment]
Well, in my opinion, if users don't want to save their modified information for some reason, there is no way to do it.
However, since it is a feature that ben has specifically added, I reserve my opinion.
I will close this isuue.
