### ISSUE TITLE
The icon that the certificate has been published on the chain is not displayed completely on some phones

### ISSUE THREAD

**Issue by xuliting** [elastos/Elastos.Trinity.DApps.DID#75]
![29461603771841_ pic_hd](https://user-images.githubusercontent.com/18321471/97256341-bb5e4d00-184d-11eb-83e1-8b2cad189817.jpg)
OPPAO A11， PCHM10

**Comment by dchagastelles** [comment]
Can you provide me the screen resolution, please?

**Comment by xuliting** [comment]
> Can you provide me the screen resolution, please?

1600* 720

**Comment by xuliting** [comment]
icon is modified
