### ISSUE TITLE
In bio's Credential details interface: bio content layout needs to be adjusted

### ISSUE THREAD

**Issue by xuliting** [elastos/Elastos.Trinity.DApps.DID#76]
![29471603773552_ pic](https://user-images.githubusercontent.com/18321471/97257642-7e945500-1851-11eb-8681-7f05de2a9917.jpg)
![29481603773553_ pic](https://user-images.githubusercontent.com/18321471/97257648-805e1880-1851-11eb-95ff-4a26b722e884.jpg)

**Comment by dchagastelles** [comment]
Will make it occupy more of the available screen.

**Comment by xuliting** [comment]
Verified
