### ISSUE TITLE
Profile：After the edited information is saved, the current interface is not automatically refreshed 

### ISSUE THREAD

**Issue by xuliting** [elastos/Elastos.Trinity.DApps.DID#77]

**Comment by dchagastelles** [comment]
From the profile page: I click in edit menu, I change the value of a credential and I return, the credential is updated.

Do you have a different behaviour?

**Comment by kpachhai** [comment]
Not sure if this is what Lemon is referring to but this is the issue I have on mine:
- I go to my avatar, turn visibility off, then click on "Hidden" tab. Yet, my avatar is not listed there
Only way to resolve this is to go back to Profile page and then come back to Credentials page then "Hidden" tab lists my avatar.

**Comment by xuliting** [comment]
> Not sure if this is what Lemon is referring to but this is the issue I have on mine:
> 
> * I go to my avatar, turn visibility off, then click on "Hidden" tab. Yet, my avatar is not listed there
>   Only way to resolve this is to go back to Profile page and then come back to Credentials page then "Hidden" tab lists my avatar.

Not referring to this problem, but the problem you mentioned does exist.
