### ISSUE TITLE
Frame of avatar: inconsistent size

### ISSUE THREAD

**Issue by xuliting** [elastos/Elastos.Trinity.DApps.DID#78]
![29491603774205_ pic](https://user-images.githubusercontent.com/18321471/97258262-0890ed80-1853-11eb-9f19-f8699b143279.jpg)
![29501603774206_ pic](https://user-images.githubusercontent.com/18321471/97258271-0cbd0b00-1853-11eb-9534-6053934184cb.jpg)

**Comment by dchagastelles** [comment]
That's weird, I can't reproduce. Do you have it in all phones?

**Comment by xuliting** [comment]
<img width="562" alt="截屏2020-11-04 18 57 24" src="https://user-images.githubusercontent.com/18321471/98103188-9ada6680-1ecf-11eb-8876-ad39f79feacf.png">

**Comment by xuliting** [comment]
OK
