### ISSUE TITLE
Change the status of whether a certain credential is public or not and return, but the category of credential is not refreshed in the Credentials column in time;

### ISSUE THREAD

**Issue by xuliting** [elastos/Elastos.Trinity.DApps.DID#80]
Change the status of whether a certain credential is public or not and return, but the category of credential is not refreshed in the Credentials column in time;
Jump to the Profile first, then enter the Credentials page, the category content is updated.

**Comment by kpachhai** [comment]
Yea, I can reproduce this same issue

**Comment by xuliting** [comment]
Verified
