### ISSUE TITLE
Color Indication on Verified/Published on Credential Screens

### ISSUE THREAD

**Issue by martintuum** [elastos/Elastos.Trinity.DApps.DID#87]
I thought this concept might be a good idea for a small visual cue for whats going on with your credentials.

When the Credential has been verified then we can have it green, if it's been published then it can be blue, and if its not published and therefore also not verified then it can be a slight grey color.

The current Zeplin file shows this. If we find this idea a good one then we can implement it.

<img width="530" alt="Screenshot 2020-11-04 at 23 32 18" src="https://user-images.githubusercontent.com/58228076/98179731-5662c100-1ef7-11eb-8391-3ff8e39d0496.png">
<img width="542" alt="Screenshot 2020-11-04 at 23 32 35" src="https://user-images.githubusercontent.com/58228076/98179740-5c58a200-1ef7-11eb-9b38-a2da92b9cd0a.png">

**Comment by kpachhai** [comment]
I like it.
