### ISSUE TITLE
Requiring a field to be mandatory does not work sometimes

### ISSUE THREAD

**Issue by kpachhai** [elastos/Elastos.Trinity.DApps.DID#92]
Eg. when an app asks for an email during credaccess intent and the user has not set their email, the credaccess screen doesn't show "email" as one of the fields to be retrieved. We should modify this behavior to always show all the fields that are marked as mandatory whether those fields are set on Identity app or not. If the field is not set, then the user shouldn't be able to get past the credaccess screen("Accept" button should be greyed out)

Note: You get an error message in this case

**Comment by wakqasahmed** [comment]
Didn't find the issue in the latest build. Seems to be fixed? @kpachhai
