### ISSUE TITLE
There is a dividing line in the tab page in dark mode, but not in light mode

### ISSUE THREAD

**Issue by xuliting** [elastos/Elastos.Trinity.DApps.DID#98]
![31191606275630_ pic_hd](https://user-images.githubusercontent.com/18321471/100180421-164d9780-2f13-11eb-8f8a-255bcbff9c5b.jpg)

**Comment by dchagastelles** [comment]
@xuliting I was not able to reproduce that line in multiple phones with different resolutions. Anyway, that's possibly a glitch in ionic ion-tab-bar control.

![image](https://user-images.githubusercontent.com/4438399/100794300-5b7a3980-33eb-11eb-9077-f800d82f72f4.png)

**Comment by xuliting** [comment]
now, it is ok
